const content={
wood:{label:'概念作品 / CRAFT',title:'木作 · 桌面秩序',body:'<p>一张桌子，容纳着工作，也容纳着生活。笔、便签与随手放下的小物，都值得一个恰好的位置。</p><h3>从使用出发</h3><p>这件桌面收纳的设计概念，把常用物件按拿取习惯分成几个区域：手边的笔、正在阅读的卡片，以及需要随时找到的小物。让收纳成为顺手的动作。</p><h3>材料的温度</h3><p>希望以胡桃木的纹理与简洁的轮廓，让器物自然融入桌面。边角、触感与比例，都应在实际制作与使用中反复调整。</p><p>这是富知野的造物方向示例，图片为概念意象，尚非已完成或在售产品。</p>'},
tool:{label:'概念作品 / DIGITAL',title:'工具 · 灵感收集',body:'<p>灵感常常只停留片刻：阅读时的一句话，散步时的一个念头，或者制作中突然出现的解法。</p><h3>先留下，再整理</h3><p>这个工具的设想，是把记录做得足够简单。先用一句话留下想法，再慢慢补充来源、关联和下一步行动。分类服务于回看，而不成为记录前的负担。</p><h3>从记录走向行动</h3><p>一条笔记可以连接一个作品，一个作品也可以回到最初的思考。积累的意义，在于有一天能把它用起来。</p><p>这里展示的是界面与产品方向概念，独立的笔记工具尚未上线。</p>'},
light:{label:'概念作品 / EVERYDAY',title:'生活 · 一盏灯的实验',body:'<p>桌边的一束光，决定了晚间阅读的氛围，也让木纹、纸张与器物的轮廓重新显现。</p><h3>观察光，也观察人</h3><p>从光落在哪里开始，思考灯的高度、灯罩的角度与桌面的关系。让光停在需要的地方，让结构保持安静。</p><h3>日常里的小实验</h3><p>木与金属、温暖与克制，可以在一件小器物里相遇。这个方向会从纸上草图开始，逐步验证材料、比例与使用感受。</p><p>这是生活器物的概念探索，图片为氛围示意，尚非已完成或在售产品。</p>'},
idea:{label:'手记 / 造物随想',title:'从一个念头，到一件作品',body:'<p>开始做一件东西，常常不需要一个宏大的理由。也许只是桌面上的笔总找不到，也许只是某个工具用起来，总有一点不顺手。</p><p>把那个小小的不方便记下来，就是起点。先不要急着寻找复杂的解决方案，试着描述清楚：它发生在什么时候？影响了哪一个动作？真正需要改变的是什么？</p><h3>让想法碰到真实的生活</h3><p>草图可以很粗糙，第一版也可以不完美。纸板、木料，或者一个只有基本功能的小页面，都能帮助我们看见想象与使用之间的距离。</p><p>使用会给出新的问题。一个边角是否硌手，一次点击是否多余，一处留白是否足够。把这些细节一点点修正，作品才慢慢有了自己的样子。</p><h3>完成，是下一次观察的开始</h3><p>好的器物会进入日常，接受时间的检验。记录那些磨损、习惯和意外，常常比为第一版做一个漂亮的解释更有价值。</p><p>富知于心，野拓于行。把知道的拿来试一试，再把做过的认真想一想。造物与求知，就这样彼此推动。</p>'},
daily:{label:'手记 / 日常观察',title:'在技术与日常之间',body:'<p>技术与生活的相遇，往往发生在很小的地方。更容易找到的一条记录、更顺手的一次操作、少一些重复劳动后空出来的一段时间。</p><h3>从一个具体的需要开始</h3><p>做工具之前，先看看真实的一天。哪些事情反复出现？哪些步骤可以简化？哪些时刻需要被认真保留？把问题说清楚，工具才有自己的方向。</p><p>技术可以帮助整理，也可以让复杂性变得更难察觉。每增加一个功能，都值得问一句：它究竟帮助了哪一个动作？</p><h3>给专注留一点空间</h3><p>一件木作需要推敲比例，一个页面需要斟酌层次。它们共同关心的，都是人与事物相处时的感受。</p><p>在工具足够顺手的时候，人可以把注意力交还给正在做的事。读一页书，完成一段思考，或者认真打磨一块木头。</p><p>富知野想持续探索的，就是这些技术、器物与日常交汇的地方。</p>'}
};
const dialog=document.querySelector('#detail');const box=dialog.querySelector('.detail-content');let opener;
document.querySelectorAll('[data-detail]').forEach(button=>button.addEventListener('click',()=>{const item=content[button.dataset.detail];opener=button;box.innerHTML=`<span class="detail-label">${item.label}</span><h2 id="detail-title">${item.title}</h2>${item.body}<p class="detail-end">富知于心，野拓于行。</p>`;dialog.showModal();dialog.scrollTop=0;document.body.classList.add('modal-open');}));
dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();});dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');opener?.focus();});
const menu=document.querySelector('.menu');const nav=document.querySelector('#nav');menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'关闭导航':'打开导航');nav.classList.toggle('open',open);});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','打开导航');}));document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','打开导航');}});
